### ISSUE TITLE
Depth estimation in inference stage

### ISSUE THREAD

**Issue by HugoNTL** [PanoDiffusion/PanoDiffusion#8]
Thank you for your excellent work. I would like to ask if it is possible to output the estimated depth maps along with the outpainting results in inference.py. I noticed that there is an argument labeled "outpainting mode, rgb or depth" in the script and was wondering if this pertains to depth map estimation. Thanks.

**Comment by PanoDiffusion** [comment]
Hi! Yes the fourth channel of the output is the depth result. You can try to also save it.
Please see [here](https://github.com/PanoDiffusion/PanoDiffusion/blob/38839b7d2d5e00d345482ce8c07be435a4001f1f/inference.py#L140).
